/**
 * Auto-generated by NodePress Type Generator CLI
 * Generated at: 2026-08-24T09:22:38.976Z
 *
 * DO NOT EDIT MANUALLY. Run `npx nodepress generate:types` to regenerate.
 */

/* ========================================================================= */
/* Base NodePress Envelope Types                                             */
/* ========================================================================= */

export interface NodePressSEO {
  title?: string;
  description?: string;
  ogImage?: string;
  canonical?: string;
  noIndex?: boolean;
}

export interface BaseEntry<TData = Record<string, any>> {
  id: string; // publicId UUID
  slug: string;
  locale: string;
  status: "draft" | "published" | "archived";
  createdAt: string;
  updatedAt: string;
  seo?: NodePressSEO;
  data: TData;
}

export interface PaginatedResponse<T> {
  data: T[];
  meta: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
    searchMode?: "fulltext" | "fallback";
  };
}

/* ========================================================================= */
/* Content Type Interfaces                                                   */
/* ========================================================================= */

/* ========================================================================= */
/* Content Type Registry                                                     */
/* ========================================================================= */

export interface NodePressContentTypes {
}

export type NodePressContentType = keyof NodePressContentTypes;
export type AnyNodePressEntry = NodePressContentTypes[NodePressContentType];
