import { FieldDef, SimpleFieldDef, FlexibleLayout } from '../fields/field.types';

export interface ContentTypeSchemaInput {
  name: string;
  label?: string;
  schema: FieldDef[] | any;
}

/** Convert snake_case or kebab-case to PascalCase */
export function toPascalCase(str: string): string {
  return str
    .replace(/[/\\_-](\w)/g, (_, c) => c.toUpperCase())
    .replace(/^\w/, (c) => c.toUpperCase());
}

/** Map simple field definitions to TypeScript types */
function mapSimpleFieldType(field: SimpleFieldDef): string {
  switch (field.type) {
    case 'text':
    case 'textarea':
    case 'richtext':
    case 'color':
    case 'date':
    case 'datetime':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'image':
      return '{ url: string; alt?: string }';
    case 'link':
      return '{ url: string; text?: string; newTab?: boolean }';
    case 'select': {
      const choices = (field as any).options?.choices;
      const isMultiple = (field as any).options?.multiple;
      if (Array.isArray(choices) && choices.length > 0) {
        const union = choices.map((c: string) => JSON.stringify(c)).join(' | ');
        return isMultiple ? `(${union})[]` : union;
      }
      return isMultiple ? 'string[]' : 'string';
    }
    case 'relation': {
      const isMany = (field as any).options?.cardinality === 'many';
      return isMany ? 'string[]' : 'string';
    }
    case 'json':
      return 'Record<string, any>';
    default:
      return 'unknown';
  }
}

/** Map any field definition (simple or complex) to TypeScript property declaration */
function mapFieldType(field: FieldDef, typePrefix: string): string {
  switch (field.type) {
    case 'repeater': {
      const subFields = (field as any).options?.subFields ?? [];
      const subTypes = subFields
        .map((sf: SimpleFieldDef) => `    ${sf.name}${sf.required ? '' : '?'}: ${mapSimpleFieldType(sf)};`)
        .join('\n');
      return `Array<{\n${subTypes}\n    _id?: string;\n  }>`;
    }
    case 'group': {
      const subFields = (field as any).options?.subFields ?? [];
      const subTypes = subFields
        .map((sf: SimpleFieldDef) => `    ${sf.name}${sf.required ? '' : '?'}: ${mapSimpleFieldType(sf)};`)
        .join('\n');
      return `{\n${subTypes}\n  }`;
    }
    case 'flexible': {
      const layouts: FlexibleLayout[] = (field as any).options?.layouts ?? [];
      if (layouts.length === 0) return 'Array<Record<string, any>>';
      const layoutUnions = layouts.map((layout) => {
        const fields = (layout.fields ?? [])
          .map((sf) => `      ${sf.name}${sf.required ? '' : '?'}: ${mapSimpleFieldType(sf)};`)
          .join('\n');
        return `    | {\n      _layout: ${JSON.stringify(layout.name)};\n${fields}\n    }`;
      });
      return `Array<\n${layoutUnions.join('\n')}\n  >`;
    }
    default:
      return mapSimpleFieldType(field as SimpleFieldDef);
  }
}

/**
 * Generate a complete, strongly-typed TypeScript definition file for all Content Types.
 *
 * @param contentTypes - Array of ContentType definitions with name and schema
 * @returns Formatted TypeScript .d.ts string
 */
export function generateTypeScriptDefinitions(contentTypes: ContentTypeSchemaInput[]): string {
  const lines: string[] = [
    '/**',
    ' * Auto-generated by NodePress Type Generator',
    ` * Generated at: ${new Date().toISOString()}`,
    ' *',
    ' * DO NOT EDIT MANUALLY. Run `npx nodepress generate:types` to regenerate.',
    ' */',
    '',
    '/* ========================================================================= */',
    '/* Base NodePress Envelope Types                                             */',
    '/* ========================================================================= */',
    '',
    'export interface NodePressSEO {',
    '  title?: string;',
    '  description?: string;',
    '  ogImage?: string;',
    '  canonical?: string;',
    '  noIndex?: boolean;',
    '}',
    '',
    'export interface BaseEntry<TData = Record<string, any>> {',
    '  id: string; // publicId UUID',
    '  slug: string;',
    '  locale: string;',
    '  status: "draft" | "published" | "archived";',
    '  createdAt: string;',
    '  updatedAt: string;',
    '  seo?: NodePressSEO;',
    '  data: TData;',
    '}',
    '',
    'export interface PaginatedResponse<T> {',
    '  data: T[];',
    '  meta: {',
    '    total: number;',
    '    page: number;',
    '    limit: number;',
    '    totalPages: number;',
    '    searchMode?: "fulltext" | "fallback";',
    '  };',
    '}',
    '',
    '/* ========================================================================= */',
    '/* Content Type Interfaces                                                   */',
    '/* ========================================================================= */',
    '',
  ];

  for (const ct of contentTypes) {
    const pascalName = toPascalCase(ct.name);
    const dataInterfaceName = `${pascalName}Data`;
    const entryInterfaceName = `${pascalName}Entry`;
    const rawSchema: FieldDef[] = Array.isArray(ct.schema) ? ct.schema : [];

    lines.push(`/** Data payload for "${ct.name}" (${ct.label || ct.name}) */`);
    lines.push(`export interface ${dataInterfaceName} {`);

    for (const field of rawSchema) {
      if (!field || !field.name) continue;
      const tsType = mapFieldType(field, pascalName);
      const optional = field.required ? '' : '?';
      const comment = field.description ? `  /** ${field.description} */\n` : '';
      lines.push(`${comment}  ${field.name}${optional}: ${tsType};`);
    }

    lines.push('}');
    lines.push('');
    lines.push(`/** Full entry wrapper for "${ct.name}" */`);
    lines.push(`export type ${entryInterfaceName} = BaseEntry<${dataInterfaceName}>;`);
    lines.push('');
  }

  // Generate Union Map
  lines.push('/* ========================================================================= */');
  lines.push('/* Content Type Registry                                                     */');
  lines.push('/* ========================================================================= */');
  lines.push('');
  lines.push('export interface NodePressContentTypes {');
  for (const ct of contentTypes) {
    const pascalName = toPascalCase(ct.name);
    lines.push(`  ${JSON.stringify(ct.name)}: ${pascalName}Entry;`);
  }
  lines.push('}');
  lines.push('');
  lines.push('export type NodePressContentType = keyof NodePressContentTypes;');
  lines.push('export type AnyNodePressEntry = NodePressContentTypes[NodePressContentType];');
  lines.push('');

  return lines.join('\n');
}
