#!/usr/bin/env bash
#
# NodePress pre-publish validation.
#
# Catches the classes of regression that would otherwise reach users, since
# GitHub Actions / CI is disabled on this account. Run this before every
# `npm publish` of the CLI (and ideally before pushing `main`).
#
# It runs in two layers:
#   A. Working-tree build  — builds backend + frontend from your LOCAL source.
#                            Catches compile errors, the backend dist path,
#                            and frontend (Next) build breakage.
#   B. Scaffold smoke      — scaffolds a throwaway project with the local CLI
#                            (which clones GitHub `main`), then verifies the
#                            generated project structure + that a single
#                            `npm install` produced a usable backend.
#   C. Runtime smoke (opt) — with --smoke and a DATABASE_URL, migrates, boots
#                            the backend, and exercises the real API end to end.
#
# Usage:
#   ./scripts/validate.sh                       # A + B  (no database needed)
#   ./scripts/validate.sh --no-scaffold         # A only (fast)
#   DATABASE_URL="postgresql://user:pass@localhost:5432/np_validate" \
#     ./scripts/validate.sh --smoke             # A + B + C
#
# Notes:
#   * Layer B reflects what's on GitHub `main` (the CLI clones it), so run it
#     after pushing for a faithful check of what users receive.
#   * The smoke test creates and drops its own database; point DATABASE_URL at
#     a throwaway name, never a real project DB.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN_SCAFFOLD=1
RUN_SMOKE=0
SMOKE_PORT="${SMOKE_PORT:-3999}"

for arg in "$@"; do
  case "$arg" in
    --no-scaffold) RUN_SCAFFOLD=0 ;;
    --smoke)       RUN_SMOKE=1 ;;
    -h|--help)     sed -n '2,33p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Unknown option: $arg" >&2; exit 2 ;;
  esac
done

# ── pretty output ────────────────────────────────────────────────────────────
if [ -t 1 ]; then G="\033[32m"; R="\033[31m"; Y="\033[33m"; B="\033[1m"; D="\033[2m"; X="\033[0m"; else G= R= Y= B= D= X=; fi
step()  { printf "\n${B}▶ %s${X}\n" "$1"; }
pass()  { printf "  ${G}✔${X} %s\n" "$1"; }
fail()  { printf "  ${R}�’✘ %s${X}\n" "$1"; FAILED=1; }
info()  { printf "  ${D}%s${X}\n" "$1"; }
FAILED=0

TMP_PROJECT=""
SMOKE_PID=""
cleanup() {
  [ -n "$SMOKE_PID" ] && kill "$SMOKE_PID" 2>/dev/null || true
  [ -n "$TMP_PROJECT" ] && [ -d "$TMP_PROJECT" ] && rm -rf "$TMP_PROJECT" || true
}
trap cleanup EXIT

# ── Layer A — working-tree build ───────────────────────────────────────────────
step "A. Working-tree build (local source)"

info "npm install (workspaces + prisma generate via postinstall)…"
( cd "$ROOT" && npm install --silent ) && pass "install + postinstall" || fail "install failed"

info "backend: type-check…"
( cd "$ROOT/backend" && npx tsc --noEmit ) && pass "backend tsc" || fail "backend tsc errors"

info "backend: production build…"
( cd "$ROOT/backend" && npm run build >/dev/null 2>&1 ) && pass "backend build" || fail "backend build failed"
if [ -f "$ROOT/backend/dist/main.js" ]; then
  pass "backend emits dist/main.js (start:prod + Docker CMD resolve)"
else
  fail "backend dist/main.js missing — start:prod / Docker would crash (check tsconfig.build.json)"
fi

info "frontend: type-check…"
( cd "$ROOT/frontend" && npx tsc --noEmit ) && pass "frontend tsc" || fail "frontend tsc errors"

info "frontend: production build (next build)…"
( cd "$ROOT/frontend" && npm run build >/dev/null 2>&1 ) && pass "frontend build" || fail "frontend build failed (stray src/ or missing deps?)"

# ── Layer B — scaffold smoke ───────────────────────────────────────────────────
if [ "$RUN_SCAFFOLD" = "1" ]; then
  step "B. Scaffold smoke (CLI → fresh project, reflects GitHub main)"
  TMP_PROJECT="$(mktemp -d)/np-validate"
  mkdir -p "$(dirname "$TMP_PROJECT")"
  info "scaffolding with local CLI (clone + install, ~1–3 min)…"
  if ( cd "$(dirname "$TMP_PROJECT")" && node "$ROOT/cli/bin/nodepress.js" np-validate >/dev/null 2>&1 ); then
    pass "scaffold completed"
  else
    fail "scaffold failed"
  fi

  PKG="$TMP_PROJECT/package.json"
  node -e "process.exit(require('$PKG').workspaces ? 0 : 1)" 2>/dev/null \
    && pass "root package.json declares workspaces" || fail "root package.json missing workspaces"
  node -e "process.exit((require('$PKG').scripts.postinstall||'').includes('prisma generate') ? 0 : 1)" 2>/dev/null \
    && pass "root postinstall runs prisma generate" || fail "root postinstall missing prisma generate"
  [ -d "$TMP_PROJECT/node_modules/.prisma/client" ] \
    && pass "Prisma client generated by install" || fail "Prisma client NOT generated (backend won't compile)"
  grep -q '^DIRECT_URL=' "$TMP_PROJECT/backend/.env" \
    && pass "backend/.env has DIRECT_URL" || fail "backend/.env missing DIRECT_URL (migrate would P1012)"
  [ ! -f "$TMP_PROJECT/docker-compose.yml" ] \
    && pass "default scaffold omits Docker files" || fail "Docker files present without --docker"
  if grep -q '@sentry/' "$TMP_PROJECT/backend/package.json" "$TMP_PROJECT/frontend/package.json" 2>/dev/null; then
    fail "default scaffold still lists @sentry deps (should be omitted without --sentry)"
  else
    pass "default scaffold omits Sentry deps (~100 MB lighter)"
  fi
  [ ! -d "$TMP_PROJECT/node_modules/@sentry" ] \
    && pass "Sentry not installed in default scaffold" || fail "@sentry present in node_modules without --sentry"
  [ ! -d "$TMP_PROJECT/backend/node_modules" ] \
    && pass "dependencies hoisted (single node_modules)" || fail "backend/node_modules not hoisted"

  info "scaffold: backend production build…"
  ( cd "$TMP_PROJECT/backend" && npm run build >/dev/null 2>&1 ) && [ -f "$TMP_PROJECT/backend/dist/main.js" ] \
    && pass "scaffold backend builds to dist/main.js" || fail "scaffold backend build/dist path broken"
fi

# ── Layer C — runtime smoke (optional) ─────────────────────────────────────────
if [ "$RUN_SMOKE" = "1" ]; then
  step "C. Runtime smoke test"
  if [ -z "${DATABASE_URL:-}" ]; then
    fail "--smoke requires a DATABASE_URL env var (throwaway DB)"
  else
    APP="$TMP_PROJECT"
    [ -z "$APP" ] && APP="$ROOT"   # fall back to working tree if scaffold skipped
    export DATABASE_URL DIRECT_URL="${DIRECT_URL:-$DATABASE_URL}" PORT="$SMOKE_PORT"
    printf 'DATABASE_URL="%s"\nDIRECT_URL="%s"\nPORT="%s"\nJWT_SECRET="validate-only-secret"\nCORS_ORIGIN="http://localhost:5173"\n' \
      "$DATABASE_URL" "$DIRECT_URL" "$SMOKE_PORT" > "$APP/backend/.env"

    info "prisma migrate deploy…"
    ( cd "$APP/backend" && npx prisma migrate deploy >/dev/null 2>&1 ) && pass "migrate" || fail "migrate failed"

    info "booting backend on :$SMOKE_PORT…"
    ( cd "$APP/backend" && node dist/main.js >/tmp/np-validate-be.log 2>&1 ) &
    SMOKE_PID=$!
    B="http://localhost:$SMOKE_PORT/api"
    n=0; until curl -sf "$B/health" >/dev/null 2>&1 || [ $n -ge 30 ]; do sleep 1; n=$((n+1)); done

    curl -sf "$B/health" >/dev/null 2>&1 && pass "health" || fail "health unreachable"
    TOK=$(curl -s -X POST "$B/auth/register" -H 'Content-Type: application/json' \
      -d '{"email":"validate@test.com","password":"Validate1234!"}' \
      | node -e "let d='';process.stdin.on('data',c=>d+=c).on('end',()=>{try{process.stdout.write(JSON.parse(d).access_token||'')}catch(e){}})")
    [ -n "$TOK" ] && pass "register + token" || fail "register failed"
    A="Authorization: Bearer $TOK"
    # Include a richtext field so the entry write path exercises sanitize-html
    # (a default-import of a CJS lib — broke at runtime when esModuleInterop was off).
    curl -s -X POST "$B/content-types" -H "$A" -H 'Content-Type: application/json' \
      -d '{"name":"vblog","schema":[{"name":"title","type":"text","label":"Title"},{"name":"body","type":"richtext","label":"Body"}]}' \
      | grep -q '"name":"vblog"' && pass "create content type" || fail "content type failed"
    ENTRY=$(curl -s -X POST "$B/entries" -H "$A" -H 'Content-Type: application/json' \
      -d '{"contentTypeId":1,"slug":"v-hello","data":{"title":"Hi","body":"<p>ok</p><script>alert(1)</script>"}}')
    echo "$ENTRY" | grep -q '"slug":"v-hello"' && pass "create entry (richtext sanitize path)" || fail "entry failed: $ENTRY"
    echo "$ENTRY" | grep -q '<script>' && fail "richtext NOT sanitized (script tag survived)" || pass "richtext sanitized (script stripped)"
    curl -s "$B/vblog/v-hello" | grep -q '"slug":"v-hello"' \
      && pass "public API returns entry" || fail "public API failed"

    info "you must drop the smoke DATABASE_URL's database yourself (script does not touch it)"
  fi
fi

# ── summary ────────────────────────────────────────────────────────────────────
echo ""
if [ "$FAILED" = "0" ]; then
  printf "${G}${B}✓ validation passed — safe to publish${X}\n"
  exit 0
else
  printf "${R}${B}✗ validation FAILED — do not publish until fixed${X}\n"
  exit 1
fi
