'use strict';

const fs = require('fs');
const path = require('path');

const GREEN = '\x1b[32m';
const CYAN  = '\x1b[36m';
const RED   = '\x1b[31m';
const BOLD  = '\x1b[1m';
const DIM   = '\x1b[2m';
const RESET = '\x1b[0m';

function ok(msg)    { console.log(`  ${GREEN}✓${RESET}  ${msg}`); }
function err(msg)   { console.error(`  ${RED}✗  ${msg}${RESET}`); }
function info(msg)  { console.log(`  ${CYAN}ℹ${RESET}  ${msg}`); }

function toPascalCase(str) {
  return str
    .replace(/[/\\_-](\w)/g, (_, c) => c.toUpperCase())
    .replace(/^\w/, (c) => c.toUpperCase());
}

function mapSimpleFieldType(field) {
  switch (field.type) {
    case 'text':
    case 'textarea':
    case 'richtext':
    case 'color':
    case 'date':
    case 'datetime':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'image':
      return '{ url: string; alt?: string }';
    case 'select': {
      const choices = field.options?.choices;
      const isMultiple = field.options?.multiple;
      if (Array.isArray(choices) && choices.length > 0) {
        const union = choices.map((c) => JSON.stringify(c)).join(' | ');
        return isMultiple ? `(${union})[]` : union;
      }
      return isMultiple ? 'string[]' : 'string';
    }
    case 'relation': {
      const isMany = field.options?.cardinality === 'many';
      return isMany ? 'string[]' : 'string';
    }
    case 'json':
      return 'Record<string, any>';
    default:
      return 'unknown';
  }
}

function mapFieldType(field, typePrefix) {
  switch (field.type) {
    case 'repeater': {
      const subFields = field.options?.subFields ?? [];
      const subTypes = subFields
        .map((sf) => `    ${sf.name}${sf.required ? '' : '?'}: ${mapSimpleFieldType(sf)};`)
        .join('\n');
      return `Array<{\n${subTypes}\n    _id?: string;\n  }>`;
    }
    case 'group': {
      const subFields = field.options?.subFields ?? [];
      const subTypes = subFields
        .map((sf) => `    ${sf.name}${sf.required ? '' : '?'}: ${mapSimpleFieldType(sf)};`)
        .join('\n');
      return `{\n${subTypes}\n  }`;
    }
    case 'flexible': {
      const layouts = field.options?.layouts ?? [];
      if (layouts.length === 0) return 'Array<Record<string, any>>';
      const layoutUnions = layouts.map((layout) => {
        const fields = (layout.fields ?? [])
          .map((sf) => `      ${sf.name}${sf.required ? '' : '?'}: ${mapSimpleFieldType(sf)};`)
          .join('\n');
        return `    | {\n      _layout: ${JSON.stringify(layout.name)};\n${fields}\n    }`;
      });
      return `Array<\n${layoutUnions.join('\n')}\n  >`;
    }
    default:
      return mapSimpleFieldType(field);
  }
}

function generateTypesString(contentTypes) {
  const lines = [
    '/**',
    ' * Auto-generated by NodePress Type Generator CLI',
    ` * Generated at: ${new Date().toISOString()}`,
    ' *',
    ' * DO NOT EDIT MANUALLY. Run `npx nodepress generate:types` to regenerate.',
    ' */',
    '',
    '/* ========================================================================= */',
    '/* Base NodePress Envelope Types                                             */',
    '/* ========================================================================= */',
    '',
    'export interface NodePressSEO {',
    '  title?: string;',
    '  description?: string;',
    '  ogImage?: string;',
    '  canonical?: string;',
    '  noIndex?: boolean;',
    '}',
    '',
    'export interface BaseEntry<TData = Record<string, any>> {',
    '  id: string; // publicId UUID',
    '  slug: string;',
    '  locale: string;',
    '  status: "draft" | "published" | "archived";',
    '  createdAt: string;',
    '  updatedAt: string;',
    '  seo?: NodePressSEO;',
    '  data: TData;',
    '}',
    '',
    'export interface PaginatedResponse<T> {',
    '  data: T[];',
    '  meta: {',
    '    total: number;',
    '    page: number;',
    '    limit: number;',
    '    totalPages: number;',
    '    searchMode?: "fulltext" | "fallback";',
    '  };',
    '}',
    '',
    '/* ========================================================================= */',
    '/* Content Type Interfaces                                                   */',
    '/* ========================================================================= */',
    '',
  ];

  for (const ct of contentTypes) {
    const pascalName = toPascalCase(ct.name);
    const dataInterfaceName = `${pascalName}Data`;
    const entryInterfaceName = `${pascalName}Entry`;
    const rawSchema = Array.isArray(ct.schema) ? ct.schema : [];

    lines.push(`/** Data payload for "${ct.name}" (${ct.label || ct.name}) */`);
    lines.push(`export interface ${dataInterfaceName} {`);

    for (const field of rawSchema) {
      if (!field || !field.name) continue;
      const tsType = mapFieldType(field, pascalName);
      const optional = field.required ? '' : '?';
      const comment = field.description ? `  /** ${field.description} */\n` : '';
      lines.push(`${comment}  ${field.name}${optional}: ${tsType};`);
    }

    lines.push('}');
    lines.push('');
    lines.push(`/** Full entry wrapper for "${ct.name}" */`);
    lines.push(`export type ${entryInterfaceName} = BaseEntry<${dataInterfaceName}>;`);
    lines.push('');
  }

  // Generate Union Map
  lines.push('/* ========================================================================= */');
  lines.push('/* Content Type Registry                                                     */');
  lines.push('/* ========================================================================= */');
  lines.push('');
  lines.push('export interface NodePressContentTypes {');
  for (const ct of contentTypes) {
    const pascalName = toPascalCase(ct.name);
    lines.push(`  ${JSON.stringify(ct.name)}: ${pascalName}Entry;`);
  }
  lines.push('}');
  lines.push('');
  lines.push('export type NodePressContentType = keyof NodePressContentTypes;');
  lines.push('export type AnyNodePressEntry = NodePressContentTypes[NodePressContentType];');
  lines.push('');

  return lines.join('\n');
}

module.exports = async function generateTypes(opts = {}, args = []) {
  console.log(`\n  ${BOLD}NodePress Type Generator${RESET}\n`);

  const cwd = process.cwd();
  let outputPath = opts.out || (fs.existsSync(path.join(cwd, 'frontend')) ? 'frontend/types/nodepress.d.ts' : 'types/nodepress.d.ts');
  const targetFile = path.isAbsolute(outputPath) ? outputPath : path.join(cwd, outputPath);

  // Load environment variables from backend/.env or .env if not present
  const envCandidates = [
    opts.env,
    path.join(cwd, 'backend', '.env'),
    path.join(cwd, '.env'),
  ].filter(Boolean);

  for (const envPath of envCandidates) {
    if (fs.existsSync(envPath)) {
      const content = fs.readFileSync(envPath, 'utf8');
      for (const line of content.split('\n')) {
        const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)?\s*$/);
        if (match) {
          const key = match[1];
          let val = (match[2] || '').trim();
          if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
            val = val.slice(1, -1);
          }
          if (!process.env[key]) {
            process.env[key] = val;
          }
        }
      }
      break;
    }
  }

  // Attempt to read schemas from database or schema files
  let contentTypes = [];

  try {
    // Try to load Prisma client from backend
    const backendPrismaPath = path.join(cwd, 'backend', 'node_modules', '@prisma', 'client');
    const rootPrismaPath = path.join(cwd, 'node_modules', '@prisma', 'client');
    let PrismaClient;

    if (fs.existsSync(backendPrismaPath)) {
      PrismaClient = require(backendPrismaPath).PrismaClient;
    } else if (fs.existsSync(rootPrismaPath)) {
      PrismaClient = require(rootPrismaPath).PrismaClient;
    }

    if (PrismaClient && process.env.DATABASE_URL) {
      const prisma = new PrismaClient();
      contentTypes = await prisma.contentType.findMany();
      await prisma.$disconnect();
    }
  } catch (e) {
    info(`Could not connect directly to database (${e.message}). Checking for exported schemas...`);
  }

  if (!contentTypes || contentTypes.length === 0) {
    // Check if schema export exists
    const schemaFile = path.join(cwd, 'nodepress-schema.json');
    if (fs.existsSync(schemaFile)) {
      try {
        contentTypes = JSON.parse(fs.readFileSync(schemaFile, 'utf8'));
        ok(`Loaded ${contentTypes.length} content type definitions from nodepress-schema.json`);
      } catch (err) {
        // ignore
      }
    }
  }

  if (!contentTypes || contentTypes.length === 0) {
    info('No content types found in database or schema file. Generating base types envelope.');
    contentTypes = [];
  }

  const outputCode = generateTypesString(contentTypes);

  // Ensure directory exists
  const outDir = path.dirname(targetFile);
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  fs.writeFileSync(targetFile, outputCode, 'utf8');
  ok(`TypeScript definitions written to: ${CYAN}${path.relative(cwd, targetFile)}${RESET} (${contentTypes.length} content types)`);
  console.log('');
};
